#See https://pre-commit.com for more information
#See https://pre-commit.com/hooks.html for more information

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-ast
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
-   repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
#        files: "\\.(py)$"
#        name: isort
#        entry: isort
#        language: python
#        types:
#          - python
#        args: [--setting-pth=pyproject.toml]
-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
#        name: black
#        entry: black
#        language: python
#        types:
#          - python
-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
#        name: flake8
#        entry: flake8
#        language: python
#        types:
#          - python
#-   repo: local
#    hooks:
#      - id: pytest
#        name: pytest
#        stages:
#          - commit
#        entry: python -m pytest -ra
#        language: python
#        additional_dependencies:
#          - pytest
#          - fastapi
#          - httpx
#      - id: coverage
#        name: coverage
#        stages:
#          - push
#        entry: coverage run
#        language: python
#        types:
#          - python
#        pass_filenames: false
-   repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
